// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6I0bPWipuog5ZAy-cbfGFMbzT-S7tds',
    appId: '1:597211099331:web:f03db4a91835fb9c05b276',
    messagingSenderId: '597211099331',
    projectId: 'capstone-majadigi-88244',
    authDomain: 'capstone-majadigi-88244.firebaseapp.com',
    storageBucket: 'capstone-majadigi-88244.firebasestorage.app',
    measurementId: 'G-LXZLLCYJQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd47eizTSF5PikD7xAtPic9D_yowYkIto',
    appId: '1:597211099331:android:23b32d381e26b4ea05b276',
    messagingSenderId: '597211099331',
    projectId: 'capstone-majadigi-88244',
    storageBucket: 'capstone-majadigi-88244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxY3uMx9eKkCb0gJQXCP8XdEUVDAMDdAs',
    appId: '1:597211099331:ios:99e568238edd46fa05b276',
    messagingSenderId: '597211099331',
    projectId: 'capstone-majadigi-88244',
    storageBucket: 'capstone-majadigi-88244.firebasestorage.app',
    iosClientId: '597211099331-ali9uf1t62lj7ms135td9fqlfpt8urqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxY3uMx9eKkCb0gJQXCP8XdEUVDAMDdAs',
    appId: '1:597211099331:ios:99e568238edd46fa05b276',
    messagingSenderId: '597211099331',
    projectId: 'capstone-majadigi-88244',
    storageBucket: 'capstone-majadigi-88244.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ6I0bPWipuog5ZAy-cbfGFMbzT-S7tds',
    appId: '1:597211099331:web:9bbdd45dcc81557d05b276',
    messagingSenderId: '597211099331',
    projectId: 'capstone-majadigi-88244',
    authDomain: 'capstone-majadigi-88244.firebaseapp.com',
    storageBucket: 'capstone-majadigi-88244.firebasestorage.app',
    measurementId: 'G-0TLW4WE6DJ',
  );

}